apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster-config
spec:
  generators:
    - git:
        repoURL: https://github.com/eximiait/cluster-config-demo
        revision: main
        files:
          - path: "argocd/config/**/*.json"
  template:
    metadata:
      name: '{{argoApplicationName}}'
    spec:
      project: default
      source:
        repoURL: '{{repoURL}}'
        path: '.'
        targetRevision: 4.9.1
        chart: ingress-nginx
        helm:
          valueFiles:
            - 'config/{{environment.name}}/{{path.basename}}/values.yaml'
      destination:
        server: '{{environment.server}}'
        namespace: '{{namespace}}'
      syncPolicy:
        syncOptions:
          - ApplyOutOfSyncOnly=true
