apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster-config
spec:
  generators:
    - git:
        repoURL: https://github.com/eximiait/cluster-config-demo
        revision: main
        files:
          - path: "argocd/config/**/*.json"
  template:
    metadata:
      name: '{{argoApplicationName}}'
    spec:
      project: default
      sources:
        - repoURL: '{{repoURL}}'
          path: '{{path}}'
          targetRevision: '{{targetRevision}}'
          chart: '{{chart}}'
          helm:
            valueFiles:
              - $values/argocd/config/{{environment.name}}/{{path.basename}}/values.yaml
        - repoURL: 'https://github.com/eximiait/cluster-config-demo'
          targetRevision: main
          ref: values
      destination:
        server: '{{environment.server}}'
        namespace: '{{namespace}}'
      syncPolicy:
        syncOptions:
          - ApplyOutOfSyncOnly=true
